const fiches = [
  {
    id: "cadre",
    title: "Se poser les bonnes questions avant d’utiliser un système d’IA",
    summary:
      "Une trame d’analyse pour évaluer la pertinence de l’IA, définir les cas d’usage et identifier les risques majeurs en amont.",
    phase: "Cadrage",
    topics: ["Stratégie", "Analyse d’impact", "Éthique"],
    organization: "DINUM / Public IA",
    link:
      "../Se poser les bonnes questions avant d’utiliser un système d'intelligence artific.pdf",
    updatedAt: "2023-10-01",
    score: 10,
  },
  {
    id: "conformite",
    title: "Se mettre en conformité",
    summary:
      "Panorama des obligations juridiques et organisationnelles applicables aux systèmes d’IA en France et en Europe.",
    phase: "Gouvernance",
    topics: ["Réglementation", "CNIL", "Documentation"],
    organization: "CNIL",
    link: "../Se mettre en conformité | CNIL.pdf",
    updatedAt: "2023-08-20",
    score: 9,
  },
  {
    id: "collecte",
    title: "Collecter et qualifier les données d’entraînement",
    summary:
      "Checklist des bonnes pratiques pour la collecte responsable des données et la préparation des jeux d’entraînement.",
    phase: "Préparation des données",
    topics: ["Données", "Qualité", "Gouvernance"],
    organization: "CNIL",
    link: "../Collecter et qualifier les données d'entraînement | CNIL.pdf",
    updatedAt: "2023-04-11",
    score: 8,
  },
  {
    id: "developper",
    title: "Développer et entraîner un algorithme",
    summary:
      "Guide opérationnel pour encadrer le développement, l’entraînement et la validation d’un modèle d’IA.",
    phase: "Développement",
    topics: ["Cycle de vie", "MLOps", "Performance"],
    organization: "CNIL",
    link: "../Développer et entraîner un algorithme | CNIL.pdf",
    updatedAt: "2022-12-05",
    score: 7,
  },
  {
    id: "securiser",
    title: "Sécuriser le traitement",
    summary:
      "Mesures techniques et organisationnelles pour sécuriser les traitements de données et prévenir les dérives.",
    phase: "Exploitation",
    topics: ["Cybersécurité", "Gestion des risques", "Conformité"],
    organization: "CNIL",
    link: "../Sécuriser le traitement | CNIL.pdf",
    updatedAt: "2023-02-14",
    score: 8,
  },
  {
    id: "production",
    title: "Utiliser un système d’IA en production",
    summary:
      "Recommandations pour assurer une mise en production fiable, expliquable et supervisée d’un système d’IA.",
    phase: "Déploiement",
    topics: ["Supervision", "Explicabilité", "Suivi"],
    organization: "CNIL",
    link: "../Utiliser un système d'IA en production | CNIL.pdf",
    updatedAt: "2023-06-18",
    score: 8,
  },
  {
    id: "droits",
    title: "Permettre le bon exercice des droits par les personnes",
    summary:
      "Fiche pratique pour garantir l’exercice effectif des droits des personnes dans les traitements d’IA.",
    phase: "Conformité",
    topics: ["Droits des personnes", "Transparence", "Consentement"],
    organization: "CNIL",
    link: "../Permettre le bon exercice de leurs droits par les personnes | CNIL.pdf",
    updatedAt: "2023-07-11",
    score: 8,
  },
  {
    id: "outils",
    title: "Outils d’analyse IA",
    summary:
      "Un panorama des outils pour auditer la performance, les biais et la robustesse des systèmes d’IA.",
    phase: "Analyse",
    topics: ["Audit", "Performance", "Biais"],
    organization: "DINUM",
    link: "../Outils analyse IA.pdf",
    updatedAt: "2023-05-03",
    score: 7,
  },
  {
    id: "generative-chatgpt",
    title: "ChatGPT : un beau parleur bien entraîné",
    summary:
      "Décryptage des modèles de langage génératifs et points de vigilance pour une utilisation responsable.",
    phase: "Exploration",
    topics: ["IA générative", "Cas d’usage", "Éthique"],
    organization: "LINC",
    link: "../[Dossier IA générative] - ChatGPT - un beau parleur bien entraîné | LINC.pdf",
    updatedAt: "2023-03-21",
    score: 6,
  },
  {
    id: "generative-regulation",
    title: "Quelles régulations pour la conception des IA génératives ?",
    summary:
      "Analyse prospective des cadres réglementaires en préparation pour les systèmes génératifs.",
    phase: "Veille",
    topics: ["Réglementation", "Veille", "IA générative"],
    organization: "LINC",
    link: "../[Dossier IA générative] - Quelles régulations pour la conception des IA générati.pdf",
    updatedAt: "2023-01-10",
    score: 6,
  },
  {
    id: "generative-practice",
    title: "De l’entraînement à la pratique : l’IA générative et ses usages",
    summary:
      "Revue des usages de l’IA générative dans les organisations et bonnes pratiques pour les maîtriser.",
    phase: "Exploration",
    topics: ["IA générative", "Cas d’usage", "Organisation"],
    organization: "LINC",
    link: "../[Dossier IA générative] - De l'entraînement à la pratique - l'IA générative et s.pdf",
    updatedAt: "2023-04-02",
    score: 6,
  },
];

const phases = [
  "Cadrage",
  "Gouvernance",
  "Préparation des données",
  "Développement",
  "Conformité",
  "Analyse",
  "Déploiement",
  "Exploitation",
  "Exploration",
  "Veille",
];

const topics = [
  "Stratégie",
  "Analyse d’impact",
  "Éthique",
  "Réglementation",
  "CNIL",
  "Documentation",
  "Données",
  "Qualité",
  "Gouvernance",
  "Cycle de vie",
  "MLOps",
  "Performance",
  "Cybersécurité",
  "Gestion des risques",
  "Supervision",
  "Explicabilité",
  "Suivi",
  "Droits des personnes",
  "Transparence",
  "Consentement",
  "Audit",
  "Biais",
  "IA générative",
  "Cas d’usage",
  "Organisation",
  "Veille",
];
